# Generated by Django 4.0.6 on 2022-07-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referenced_tweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referenced_tweet', to='db.tweet')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet', to='db.tweet')),
            ],
            options={
                'db_table': 'quoted_tweet_mapping',
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('tweet',), name='unique tweet'),
        ),
    ]
