# Generated by Django 4.0.6 on 2022-07-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_replied_retweet_remove_quote_unique tweet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                default=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="db.author",
            ),
        ),
    ]
