# Generated by Django 4.0.6 on 2022-07-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_alter_tweet_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                db_constraint=False,
                default=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="db.author",
            ),
        ),
    ]
