# Generated by Django 4.0.6 on 2022-07-29 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0010_alter_quote_tweet_alter_retweet_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="followers_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="listed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="location",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="author",
            name="pinned_tweet",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pinned_tweet_of_user",
                to="db.tweet",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="profile_image_url",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="protected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="author",
            name="tweet_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="author",
            name="url",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="username",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="author",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="author",
            field=models.ForeignKey(
                db_constraint=False,
                default=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="author_of_tweet",
                to="db.author",
            ),
        ),
    ]
